name: First Workflow
on: workflow_dispatch
jobs:
  First-Job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
            echo "Hello World!"
            echo "Good-bye!"
  
